### ISSUE TITLE
Error for test definition "expired_access_token" 

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/NumberVerification#147]
**Problem description**
We have probably an issue for @NumberVerification_phone_number_share202_expired_access_token

Accordingly to the guideline and consistently with other API in v1.0 as sim swap, location verification, otp, it should be error `code` `UNAUTHENTICATED` and not `AUTHENTICATION_REQUIRED` as describe in both feature files. 

**Expected behavior**
Fix both feature files.

**Alternative solution**

**Additional context**
cc @trehman-gsma as it has impact on the certification process.
@fernandopradocabrillo and @AxelNennker to get your feedback

**Comment by fernandopradocabrillo** [comment]
Hi @bigludo7 
Yes, I agree, this is something I had in mind when reviewing the [test definitions PR](https://github.com/camaraproject/NumberVerification/pull/124#discussion_r1725023961) but due to time constrains I kind of forgot to track.. thanks for bringing it up.

I also think it should be UNAUTHENTICATED for consistency and there should be a more clear guideline on when to use each of the errors.

**Comment by bigludo7** [comment]
Thanks @fernandopradocabrillo 
Do we craft a r1.3?
Adding @hdamker to get his feedback -This is not strictly a bug but more a inconsistency that have impact on the certification process
