### ISSUE TITLE
Change Name of API to "Number Verify"

### ISSUE THREAD

**Issue by hdamker** [camaraproject/NumberVerification#62]
**Problem description**

While the name of the API family is correct with NumberVerification the current API needs to meet the name "Number Verify" as used by several operators already.

**Expected behavior**

Change title, base path, and documentation appropriatly. Keep schema names where possible (not need to change them).

**Alternative solution**

n/a

**Additional context**

**Comment by diegogonmar** [comment]
Hi @hdamker,
Changing API name is a breaking change. Actually its even more, it's defining a different API. I think there is no justification to do this.
In Telefonica we have implemented several months ago the API according to CAMARA spec, we're not willing to change it.

**Comment by hdamker** [comment]
@diegogonmar thanks for your comment, will bring you in contact with your colleagues who asked for this change.

**Comment by hdamker** [comment]
Hi @diegogonmar as this was also a ask from Telefonica colleagues I thought it is now the right time before we have a first release of the API. There is no release, so there can't be a breaking change?

**Comment by DT-DawidWroblewski** [comment]
Current naming of API is confusing, as we're having a commercial offering under [Number Verify](https://www.numberverify.org/). Due to the investment done in marketing of this brand - it is a fair suggestion from Local Champion Germany to replace "Number Verification" with "Number Verify".

I agree with @hdamker that unless there is release, there are no braking changes.

**Comment by hdamker** [comment]
Note: Deleted two comments which referred to a none public discussion of OGW and will close the issue as there is first the need to get clarity about the right API name.
