### ISSUE TITLE
Proposal to protect the "OAuth2 AuthCode Grant authorisation request" endpoint

### ISSUE THREAD

**Issue by mhfoo** [camaraproject/NumberVerification#71]
**Problem description**

Referring to the following [sequence diagram](https://github.com/camaraproject/NumberVerification/blob/main/documentation/API_documentation/assets/uml_v0.3.jpg),
is the endpoint "OAuth2 AuthCode Grant authorisation request (prompt=none&redirect_uri)" on the AuthServer protected?

**Possible evolution**
Proposal to have a one-time use token to prevent abuse of this un-protected endpoint on AuthServer.
The App Backend will need to obtain this one-time use token from the AuthServer and pass it to the Device App.

Proposal as attached:
![Proposal](https://github.com/camaraproject/NumberVerification/assets/134043190/b83ef4a8-62e6-4422-9e1c-343da9b135d2)

**Comment by mhfoo** [comment]
@mhfoo will use a reference diagram from OGW to illustrate aggregators

**Comment by mhfoo** [comment]
**Standalone Example**
![Proposal (1)](https://github.com/camaraproject/NumberVerification/assets/134043190/1ee0cfb5-4544-498c-adff-b186b5aa49b9)

**Federated Example**
![Simple Federated Proposal](https://github.com/camaraproject/NumberVerification/assets/134043190/7fb66d4d-8ae0-460f-a545-66ec48ce93b6)

**Comment by mhfoo** [comment]
@mhfoo will append the complete flows for illustration purpose.

**Comment by mhfoo** [comment]
![Federated Architecture-Network Auth Service](https://github.com/camaraproject/NumberVerification/assets/134043190/9cdc146a-afd7-4ba9-9f14-2d6d789952ec)

@sfnuser 
Referencing the above diagram; this is to solve the following points.

1. A bad actor can perform a DDOS attack with multiple Operator Y SIM cards on Operator Y /authorize endpoint - light blue dash route; this is an internal mobile network route without traversing the Internet. The one-time use token will be validated at the Auth Service, and therefore protecting the downstream network nodes.

2. Aggregators are using mobile apps to query different operator /authorize endpoints to discover (at no cost) which operator the SIM card belongs too. The one-time use token will be associated with an Application Backend for charging purposes.

**Comment by mhfoo** [comment]
Standalone
![Proposal (1)](https://github.com/camaraproject/NumberVerification/assets/134043190/9bcdbd4e-28f8-4f80-8a47-7fb42dfc7f24)

Federated
![Simple Federated Proposal](https://github.com/camaraproject/NumberVerification/assets/134043190/72646f4d-0c52-4f98-8783-e3d9a0162a43)

@DT-DawidWroblewski as requested above.

**Comment by mhfoo** [comment]
Standalone:
[Proposal.txt](https://github.com/camaraproject/NumberVerification/files/14205866/Proposal.txt)

Federated:
[Simple Federated Proposal.txt](https://github.com/camaraproject/NumberVerification/files/14205868/Simple.Federated.Proposal.txt)

**Comment by fernandopradocabrillo** [comment]
@mhfoo This proposal is defining a pre-step to the number verification API call, which I believe is in the scope of authN authZ. Perhaps this topic fits better in the I&C working group, as it can be applied to more APIs.

**Comment by mhfoo** [comment]
> @mhfoo This proposal is defining a pre-step to the number verification API call, which I believe is in the scope of authN authZ. Perhaps this topic fits better in the I&C working group, as it can be applied to more APIs.

Yes, agree.
Number verification is the first intended CAMARA API application (for Singtel) to "fix".

Once this sub project does not have any objection or further clarifications. I will raise to both I&C working group and GSMA Open Gateway, Chapter 6.

**Comment by fernandopradocabrillo** [comment]
> Once this sub project does not have any objection or further clarifications. I will raise to both I&C working group and GSMA Open Gateway, Chapter 6.

I think the process should be the other way around. If it is something specific to number verification it makes sense, but this is something generic to all apis. In my opinion the first thing should be to present the proposal to I&C and GSMA and then go to the WG to apply it. It won't do much good if there are no objections here but when it gets to I&C the proposal doesn't fit. Or if there are objections in other subgroups.

**Comment by mhfoo** [comment]
@fernandopradocabrillo 
To my understanding, Authorization Code Flow (Auth Code Flow) is used in the Number Verification APIs. I am not aware if other CAMARA APIs are using this Auth Code Flow.

This proposal is to protect the /authorize endpoint in the Number Verification use case, based on the Auth Code Flow.

The rest of the CAMARA APIs are using CIBA or Client Credentials flows. The OIDC profile is being discussed [here](https://github.com/camaraproject/IdentityAndConsentManagement/blob/3a17b29fc1d18f8e8c2816b5fdb655885b8cb02c/documentation/CAMARA-OIDC-profile.md)

I will raise in I&C and GSMA in due time, waiting until the baseline OIDC profile is defined. 

FYI: This will impact the CAMARA certification for Number Verification, as this is a security concern.

**Comment by AxelNennker** [comment]
> @fernandopradocabrillo To my understanding, Authorization Code Flow (Auth Code Flow) is used in the Number Verification APIs. I am not aware if other CAMARA APIs are using this Auth Code Flow.

Hi @mhfoo 
All Camara APIs that need user consent MUST use authorization code flow. 

If user consent is not "needed", for whatever reason, the API is protected by oauth2 client credentials flow.
NumberVerify has this https://github.com/camaraproject/NumberVerification/blob/release-0.3.1/code/API_definitions/CAMARA/number_verification.yaml#L147
```javascript
  securitySchemes:
    three_legged:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```
And the same security scheme in their main branch https://github.com/camaraproject/NumberVerification/blob/main/code/API_definitions/number_verification.yaml#L158 Just the name changed.
```javascript
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```

Regarding prompt=none:

OIDC says 

> "An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request."

And

> When possible, an id_token_hint SHOULD be present when prompt=none is used and an invalid_request error MAY be returned if it is not

So, normal non-telco AZ need a way to determine who the sub is. This is either done through cookies or a id_token_hint.
Neither is mentioned in the issue. How does the AZ determine the sub and whether they are logged-in?
If there is neither a id_token nor a cookie, then the AZ can return an error because the `conditions of the request are not fulfilled`.

If the client already has an id_token, then the id_token was granted by the same AZ and spraying all known AZ with prompt=none requests is unnecessary because the requester already knows the answer the home-grown telco-finder might solve.

Does requiring the id_token solve this issue?

Or am I missing the problem?

**Comment by diegogonmar** [comment]
@AxelNennker why you say that AuthCode is a must in every CAMARA API if consent is needed? What about CIBA? Please clarify your message as is asserting some points that may cause confusion
Also the sentence about Client Credentials if consent is not needed may be misleading. 
I'd suggest to better refer to Identity&Consent documentation, where this information is included.

@mhfoo regarding this API, yes AuthCode was set as the only valid option as this API is strictly related with silent (network-based) authentication. As indicated [here](https://github.com/camaraproject/NumberVerification?tab=readme-ov-file#scope) API is to _verify the phone number associated with the SIM used in the device connected to the mobile data network._. Other CAMARA APIs can use AuthCode unless otherwise stated in each API indicating a reason not to allow it

**Comment by mhfoo** [comment]
Hi @AxelNennker :

Agree with @diegogonmar comments above.

Using the following [diagram](https://github.com/camaraproject/NumberVerification/issues/71#issuecomment-1922732575) as context.

The following are the concerns:
`/authorize` endpoint does not require any form of authentication to invoke this API.

1. Any entity can invoke this public API to cause a DDoS attack - light blue dash route
2. A trusted entity (e.g an aggregator) can use this endpoint of multiple different operators to determine the operator of a SIM card, at no cost, without continuing the auth code flow. 
Example: If this endpoint response successfully with a redirect 302, the SIM card belongs to this operator. If this endpoint response with an error, the SIM card may not belong to this operator.

For point 1. above, I believe garciasolero is addressing it in [IdentityAndConsentManagement: issue 128](https://github.com/camaraproject/IdentityAndConsentManagement/issues/128)

Let's connect in [IdentityAndConsentManagement: issue 128](https://github.com/camaraproject/IdentityAndConsentManagement/issues/128).

**Comment by mhfoo** [comment]
@DT-DawidWroblewski please refer to [IdentityAndConsentManagement Issue 128](https://github.com/camaraproject/IdentityAndConsentManagement/issues/128#issuecomment-1964442751)

I agree with the proposal to use [RFC9101](https://www.rfc-editor.org/rfc/rfc9101.html#name-passing-a-request-object-by)

Will drop issue #71.
