### ISSUE TITLE
Usage of AMR in the spec

### ISSUE THREAD

**Issue by sfnuser** [camaraproject/NumberVerification#81]
**Problem description**
Both `/verify` and `/device-phone-number` endpoints talk about AMR value in the error code - `In order to check the authentication method, AMR parameter value in the 3-legged user's access token`

- Does that mean `ID token` is mandatory? If so, should `openid` is added to the scope of these endpoints?

**Expected behavior**
Clarify and update specification

**Comment by DT-DawidWroblewski** [comment]
Please refer to [PR#113 at ID&C](https://github.com/camaraproject/IdentityAndConsentManagement/pull/113)

**Comment by DT-DawidWroblewski** [comment]
Hi!

This issue is a part of discussion around new Camara OIDC profile, that you can find here:
1) [Identity & Consent Management PR#121](https://github.com/camaraproject/IdentityAndConsentManagement/pull/121)
2) [Identity & Consent Management PR#113](https://github.com/camaraproject/IdentityAndConsentManagement/pull/113)

Outcome is expected, so API definitions can be updated with a proper information about what query parameters are required for each product invokation over Camara API.

Therefore, please continue discussion there.

Thx!
