### ISSUE TITLE
Authorization request parameters in the sequence diagram - clarification

### ISSUE THREAD

**Issue by sfnuser** [camaraproject/NumberVerification#82]
**Problem description**
Any reason why the sequence diagram mentions about `prompt=none, redirect_uri` parameters alone in the Authorization request?
While `prompt` is optional parameter and it makes sense to add it as it is mandatory here but why `redirect_uri`?

**Expected behavior**
Update specification with clarification

**Additional context**
It can cause confusion to developers that we explicitly mention one required parameter alone without any clarification and leave the others

**Comment by DT-DawidWroblewski** [comment]
Hi!

This issue is a part of discussion around new Camara OIDC profile, that you can find here:
1) [Identity & Consent Management PR#121](https://github.com/camaraproject/IdentityAndConsentManagement/pull/121)
2) [Identity & Consent Management PR#113](https://github.com/camaraproject/IdentityAndConsentManagement/pull/113)

Outcome is expected, so API definitions can be updated with a proper information about what query parameters are required for each product invokation over Camara API.

Therefore, please continue discussion there.

Thx!
